title: Books
default_lang: th
author:
  name: 'Ishmael Dos'
  email: nukboon@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='

blog:
  route: /blog

logo: https://demo.getgrav.org/mediator-skeleton/user/images/logo.jpg

# author:
#     name: Bill Bloggs
#     email: a-mail@mail.mail
#     image: /user/images/avatar.jpg
#     bio: I'm a blogger and a Grav-lover

social:
    - icon: twitter
      url: https://twitter.com/getgrav
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: "?text="
      share_link: "&amp;url="

    - icon:  facebook
      url:   https://facebook.com/???
      desc: Connect with me facebook
      share_url: //www.facebook.com/sharer.php
      share_title: "?t="
      share_link: "&amp;u="

    - icon: github
      url: https://github.com/getgrav
      desc: Fork me on github
      share_url:
      share_title:
      share_link:

    - icon:  google-plus
      url:   https://google.com/???
      desc:  Add me on google+
      share_url:
      share_title:
      share_link:
